name: Android CI using Fastlane

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Fastlane Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Setup Java environment
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Load Maps API Key from secrets
      env:
        MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
      run: echo MAPS_API_KEY=\"MAPS_API_KEY\" > ./local.properties

    - name: Load Firebase config file from secrets
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $GOOGLE_SERVICES_JSON > /home/runner/work/xpense/xpense/app/google-services.json

    - name: Setup fastlane
      run: bundle install

    - name: Create service-account-2.json
      id: createServiceAccount
      run: echo '${{ secrets.SERVICE_ACCOUNT_2_JSON }}' > service-account-2.json

      # Build AAB and upload to Play Store
    - name: Build and Deploy
      id: buildRelease
      run: bundle exec fastlane aab_play_store

#  deploy:
#    name: Fastlane Deploy
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#
#    # Setup Java environment
#    - name: set up JDK 11
#      uses: actions/setup-java@v3
#      with:
#        java-version: '11'
#        distribution: 'temurin'
#        cache: gradle
#
#    - name: Setup fastlane
#      run: bundle install
#
#    # Upload to Play Store
#    - name: Build AAB and upload to Play Store
#      run: bundle exec fastlane aab_play_store
